### PR TITLE
Removed andand dependency

### PR DESCRIPTION
**Pull request by cjmarkham**
The `andand` gem was causing us issues at compile [1] time so I removed the dependency while keeping functionality.

[1] 
```
/rof/cache/bundler/ruby/2.2.0/gems/andand-1.3.3/lib/andand.rb:66: [BUG] Stack consistency error (sp: 193, bp: 192)
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
```

### CODE REVIEW

**Comment by gorn** [comment]
I am not persuaded  that removing andand is not bad for readibility and effectivness. Also your error looks supicious there is 2.2.0 as well as 2.2.3 ruby version mentioned at the same line. Are you sure that you are not mixing up two verions of ruby? ... and do not get me wrong, I am really interested in your change, because it can point to some wierd mistakes in the code under some verions of ruby, which I want to avoid. Can you post what steps you followed while trying to compile the code (I am not sure I understand what it means in terms of ruby). 

Inspired by your error I have added some verions of ruby to automatic testing, but everything seems to [work fine](https://travis-ci.org/gorn/rspreadsheet/builds/87939351)

**Comment by cjmarkham** [comment]
I think the issue is a conflict with `andand` and `Nokogiri` since we use both and both make use of `libxml-ruby`.

**Comment by gorn** [comment]
Andand uses ruby-libxml? Isn;t it mixed up derectly to Object? I see no reason why it should do so ... there should be another mistake.


PS: You are right with folders, my bad.

**Comment by cjmarkham** [comment]
Ignore that comment about `andand` using `ruby-libxml` it was wrong. I will do some debugging tomorrow in an isolated environment to determine why `andand` was causing issues with our stack. Removing it did solve the problem though. I will let you know what I find.

**Comment by gorn** [comment]
Ok, I am closing this pull request for now, but let me know if you find something.

**Pull request closed without merging**
