### PR TITLE
fixes #25

### LINKED ISSUE #25: Trying to use rspreadsheet cloned in OpenBSD/adJ produces "sh: dpkg-query: not found" when running bundle install
I cloned rspreadsheet and in another directory I started an example  with this Gemfile:
              
gem 'rspreadsheet', path: '../rspreadsheet'
gem 'libxml-ruby', '2.8.0'

When I run bundle install I obtain
sh: dpkg-query: not found  

My platform is adJ/OpenBSD 6.0.

### PR DESCRIPTION
**Pull request by vtamara**

### CODE REVIEW

**Comment by gorn** [comment]
Thanks for you contribution and for the bug report. I need your help to finetune this, because although your pull request is resolving the bug, it slightly degrades the original code. The intention was to check, whether the package `ruby-libxml` is installed on debian like OSes *using its internal package system* (apt,aptitude,dpkg) and only if it is NOT installed, than install the gem `libxml-ruby`. Now it checkes whether the gem `ruby-libxml` is installed ... see the difference. I am not familar with BSD packaginf system. What would be the most universal way to check whether the package ruby-libxml is installed (not the gem) or how the package providing ruby bindings for libxml is named.

**Comment by gorn** [comment]
can you please test that this command

> pkg_info -q -e ruby-libxml

checks whether the package `ruby-libxml` is installed?

**Comment by gorn** [comment]
Also can you please test that this command

> pkg_info -q -e ruby-libxml

checks whether the package `ruby-libxml` is installed? (on openBSD)

**Comment by vtamara** [comment]
In OpenBSD/adJ you could do: 

```
pkg_info | grep ruby-libxml
```

That returns 0 in $? if there is installed a package with the name ruby-libxml.  However:

1. There is no package for OpenBSD with that name (see http://ports.su/ )
2. There is no package for OpenBSD that includes the gem libxml-ruby  (there are a few packages for few gems ---that personally I don't use by the way).
3. Each operating system has its own package utilities, for some there can be package for certain gems but not for others. 

In OpenBSD/adJ the packages with gems will add the gem in the standard directory for gems (e.g /usr/local/lib/ruby/gems/2.4/gems/), and finally the gem is ```registered``` and visible from command line with ```gem list``` and from a ruby application it is available in Gem::Specification (see ```ruby -e 'puts Gem::Specification.all_names()'```).

I wonder if in Debian is not the same way?  I wish it would be enough to test the presence of the gem from ruby, not certaing package in a particular operating system.   That was the intention of the patch, hoping it could work.

**Comment by vtamara** [comment]
By the way:
```
$ pkg_info -q -e ruby-libxml
Invalid spec: ruby-libxml
```
You could check for any version with:
```
pkg_info -q -e 'ruby-libxml-*'
```

**Comment by gorn** [comment]
If I wanted to test if the gem is installed or not, than its very easy and in fact this is what I do for all other gems rspreadsheet depends on. It is done by just saying `gem gemname`. If the native packaging system registers gem so it is visible with gem list than nothing more is needed. However the deb package does not do that (at least to my knowledge) so one must check for it. It is dirty, but better than conflict of two ruby-libxml versions installed at the same time.

Note that I check for the ruby-libxml gem after having found that there is no trace of native package "detectable". I took the idea from your code that it should deal with errors when the dpkg is nor installed at all and incorporated this part of your pull request into the main branch.

**Comment by gorn** [comment]
commit 0f6d414 contains more, I wont do another release, so please git pull it from github

**Comment by vtamara** [comment]
Since this problem seems specific of Debian, wouldn't be better to detect if running on it before performing actions with packages?.  For example I think it is possible to detect linux with:

if RUBY_PLATFORM =~ /linux/
  puts "Running on linux"
end

**Comment by gorn** [comment]
I think that this is quire resolved as it is now - it checks for the native package and than for the gem.

**Pull request closed without merging**
